version: '3.5'

services:
  kotlin-restful-api-mysql:
    container_name: "kotlin-restful-api-mysql"
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: strongrootpassword
      MYSQL_DATABASE: restful-api
      MYSQL_USER: alian
      MYSQL_PASSWORD: strongrootpassword
      MYSQL_HOST: 127.0.0.1
